language: c
dist: xenial
sudo: required
compiler:
  - gcc
  - clang
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-server-dev-10
env:
  matrix:
    - LIBVERSION=master
    - LIBVERSION=2.7.0
    - LIBVERSION=2.6.0
before_install:
  - wget -qO- https://github.com/repology/libversion/archive/$LIBVERSION.tar.gz | tar -xzf- && ( cd libversion-$LIBVERSION && cmake . && make && sudo make install && sudo ldconfig )
script:
  - make
  - sudo make install
  - make installcheck
  - if test -e regression.diffs; then cat regression.diffs; fi

  - sudo -u postgres psql -c "CREATE DATABASE ext_test1;"
  - sudo -u postgres psql -d ext_test1 -c "CREATE EXTENSION libversion"
  - sudo -u postgres psql -d ext_test1 -c "SELECT pg_catalog.pg_describe_object(classid, objid, 0) FROM pg_catalog.pg_depend WHERE refclassid = 'pg_catalog.pg_extension'::pg_catalog.regclass AND refobjid = (SELECT oid FROM pg_catalog.pg_extension WHERE extname='libversion') and deptype='e' order by 1" > extension_contents.a

  - sudo -u postgres psql -c "CREATE DATABASE ext_test2;"
  - sudo -u postgres psql -d ext_test2 -c "CREATE EXTENSION libversion VERSION '1.0.0'"
  - sudo -u postgres psql -d ext_test2 -c "ALTER EXTENSION libversion UPDATE"
  - sudo -u postgres psql -d ext_test2 -c "SELECT pg_catalog.pg_describe_object(classid, objid, 0) FROM pg_catalog.pg_depend WHERE refclassid = 'pg_catalog.pg_extension'::pg_catalog.regclass AND refobjid = (SELECT oid FROM pg_catalog.pg_extension WHERE extname='libversion') and deptype='e' order by 1" > extension_contents.b

  - if cmp -s extension_contents.a extension_contents.b; then echo "Extension update check passed"; else echo "Extension update sanity check failed!"; diff -u extension_contents.a extension_contents.b; false; fi
