language: c
dist: bionic
sudo: required
matrix:
  include:
    # base
    - env: POSTGRESQL=12 LIBVERSION=master
    # libversion versions
    - env: POSTGRESQL=12 LIBVERSION=3.0.1
    - env: POSTGRESQL=12 LIBVERSION=3.0.0
    # compilers
    - env: POSTGRESQL=12 LIBVERSION=master
      compiler: gcc
    - env: POSTGRESQL=12 LIBVERSION=master
      compiler: clang
    # PostgreSQL versions
    - env: POSTGRESQL=11 LIBVERSION=master
    - env: POSTGRESQL=10 LIBVERSION=master
before_install:
  - sudo service postgresql stop
  - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-$POSTGRESQL postgresql-server-dev-$POSTGRESQL
  - sudo sed -i -e 's|#*port = .*|port = 5432|' /etc/postgresql/$POSTGRESQL/main/postgresql.conf
  - sudo sed -i -e 's|peer|trust|' /etc/postgresql/$POSTGRESQL/main/pg_hba.conf
  - sudo pg_ctlcluster $POSTGRESQL main restart
  - sudo -u postgres createuser -s "$USER"

  - wget -qO- https://github.com/repology/libversion/archive/$LIBVERSION.tar.gz | tar -xzf- && ( cd libversion-$LIBVERSION && cmake . && make && sudo make install && sudo ldconfig )
script:
  - make
  - sudo make install
  - make installcheck
  - if test -e regression.diffs; then cat regression.diffs; fi
