\echo Use "ALTER EXTENSION libversion UPDATE TO '2.0'" to load this file. \quit

DROP FUNCTION version_compare_simple(text, text);

CREATE FUNCTION VERSIONFLAG_LOWER_BOUND()
RETURNS int4
AS '$libdir/libversion', 'wrap_VERSIONFLAG_LOWER_BOUND'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION VERSIONFLAG_UPPER_BOUND()
RETURNS int4
AS '$libdir/libversion', 'wrap_VERSIONFLAG_UPPER_BOUND'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
